name = "payupnow-api"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat_v2"]
minify = true

[dev]
port = 5001

[vars]
BOT_INFO = """{
    "id":7014456183,
    "is_bot":true,
    "first_name":"PayUpNow",
    "username":"PayUpNowBot",
    "can_join_groups":true,
    "can_read_all_group_messages":false,
    "supports_inline_queries":false,
    "can_connect_to_business":false,
    "has_main_web_app":false
}"""

[[d1_databases]]
binding = "DB"
database_name = "payupnow-db"
database_id = "a67b942e-b48b-4483-bb4b-6c78c510c53c"
migrations_dir = "./drizzle"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"